#include "arduino_secrets.h"
/*
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/0a561726-ca16-430d-85d4-b28ada7b91e9 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  CloudLight led1;
  CloudLight led2;
  CloudLight led3;
  CloudLight led4;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

void setup() {
  //myservo.attach(D8);
  //servoMain.attach();
  pinMode(D2,OUTPUT);
  pinMode(D3,OUTPUT);
  pinMode(D4,OUTPUT);
  pinMode(D5,OUTPUT);
  pinMode(D6,OUTPUT);

  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 
  digitalWrite(D2,LOW);
  digitalWrite(D3,LOW);
  digitalWrite(D4,LOW);
  digitalWrite(D5,LOW);

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
}


/*
  Since Led is READ_WRITE variable, onLedChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onLedChange()  {
 
  // Add your code here to act upon Led change
}

/*
  Since Led1 is READ_WRITE variable, onLed1Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onLed1Change()  {
  if(led1 == 0){
    digitalWrite(D2,HIGH);
  }else{
    digitalWrite(D2,LOW);
  }
  // Add your code here to act upon Led1 change
}

/*
  Since Led2 is READ_WRITE variable, onLed2Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onLed2Change()  {
  if(led2 == 0){
    digitalWrite(D3,HIGH);
  }else{
    digitalWrite(D3,LOW);
  }
  // Add your code here to act upon Led2 change
}

/*
  Since Led3 is READ_WRITE variable, onLed3Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onLed3Change()  {
  if(led3 == 0){
    digitalWrite(D4,HIGH);
  }else{
    digitalWrite(D4,LOW);
  }
  // Add your code here to act upon Led3 change
}


/*
  Since Position is READ_WRITE variable, onPositionChange() is
  executed every time a new value is received from IoT Cloud.
*/


void onHumidityChange() {
// Do something
 
}
 
void onMsgChange() {
// Do something
}

/*
  Since Led4 is READ_WRITE variable, onLed4Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onLed4Change()  {
  if(led4 == 0){
    digitalWrite(D5,HIGH);
  }else{
    digitalWrite(D5,LOW);
  }
  // Add your code here to act upon Led4 change
}

/*
  Since Led5 is READ_WRITE variable, onLed5Change() is
  executed every time a new value is received from IoT Cloud.
*/





